### ISSUE TITLE
et le gameplay alors ? ;)

### ISSUE THREAD

**Issue by davidmarsprof** [Brieux/unserious-game#1]
Bon ok c'est du bon boulot, on voit que t'as de bonnes bases mais... 

N'oublie pas que le principe d'un quiz c'est une succession de questions assez minimales, c'est un tunnel où on n'a pas d'autres choix que de passer d'une question à l'autre. Si tu mets un menu qui permet de passer d'une question à l'autre à tout moment tu casses le gameplay.

**Comment by Brieux** [comment]
Disons que le menu était plus la pour mettre en place en header, je vais essayer de mettre tout le site en récursive aussi, notamment le header. Après je pense que je permettrai seulement de revenir sur les questions précédentes dans le menu

**Comment by davidmarsprof** [comment]
en _récursive_ ??? tu veux dire _responsive_ non ? ;)
